os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  postgresql: "10"
  apt:
    update: true
    packages:
      # ScanPipe "graph" management command dependency
      - graphviz
      # ScanCode-toolkit dependencies
      - xz-utils
      - zlib1g
      - libxml2-dev
      - libxslt1-dev
      - bzip2

env:
  global:
    - SCANCODEIO_DB_USER=postgres
    # Run tasks in the current thread, no need to start workers in CI mode
    - CELERY_TASK_ALWAYS_EAGER=True
    # Bypass the virtualenv activation in Makefile commands
    - ACTIVATE=

install:
  - make dev
  - make envfile
  - make check

before_script:
  - createdb --encoding=utf-8 scancodeio

script: ./manage.py test --settings=scancodeio.settings.base --verbosity=2 --noinput
